### ISSUE TITLE
rt-start fails on Mac M1

### ISSUE THREAD

**Issue by cianoc** [titola/incudine#6]
When running incudine, 
(rt-start) fails with the following exception:
```
arithmetic error DIVISION-BY-ZERO signalled
   [Condition of type DIVISION-BY-ZERO]
```
This seems to be a regression caused by the last change to the rt.lisp file. It was working previously.

This is on a Mac using the M1 chip.

Thanks.

**Comment by titola** [comment]
Do you get the same problem after

```
cd incudine/src
./clean.sh
```

and recompilation?

I remember a similar report here:

https://sourceforge.net/p/incudine/mailman/incudine-devel/thread/a0558c7f-29ba-7168-3a5d-9cf5a4e8a772%40parkellipsen.de/#msg36210513

The change in rt.lisp for non-windows is the structure RT-PARAMS moved from
config.lisp.

Il giorno sab 6 mag 2023 alle ore 01:31 cianoc ***@***.***>
ha scritto:

**Comment by cianoc** [comment]
I just tried that, along with deleting the contents of ~/.cache/common-lisp

It gave me the same error. The only other thing I get when compiling is:

```
ld: warning: directory not found for option '-L/opt/local/lib/'
```

But there are no errors about libraries not being found, so I don't think that's it.

**Comment by cianoc** [comment]
Okay having just tried an earlier commit that I'm fairly sure did work, I get the same error. I wonder if there's something else going on to do with my computer, but I'm at a bit of a loss.

**Comment by cianoc** [comment]
Okay I seem to be making progress. This may be user error, in which case apologies.

**Comment by cianoc** [comment]
This seems to have been a combination of an OSX update, an SBCL update and stale files. Apologies for the noise.
